winglessraven/AMP-Discord-Bot

DiscordBotPlugin/PluginMain.cs
* Add help command to show possible commands
* Clear user cache before checking roles to ensure latest is grabbed
=> Add help command and clear user cache before checking roles

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs
* Add buttons to @bot info message
* Option to log button clicks to another channel for moderation purposes
* Make info message dynamically update
* Add option to post user join and leave events to a channel (#4 )
=> Various Changes

DiscordBotPlugin/PluginMain.cs
Bug fix - only run stop command from button click once
=> Only run stop button command once!

DiscordBotPlugin/PluginMain.cs
Send console commands with `@[bot name] console command to send`
=> Can now send commands to the server console (if server supports it)

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs
* Add option to replace default application state values with custom text
* Add option to replace bot presence when server is online with custom text
=> Add Option to Replace Default State

DiscordBotPlugin/PluginMain.cs
Adds function to make sure the playtime count is cleared if the player leave event wasn't registered due to crash or other reasons.
=> Make sure playtime count stops when server is not online 

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md
Move away from picking up chat messages with the bot tag to use / commands within Discord.
=> Move away from text chat commands to Discord commands

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs
Move playtime command outside permission check.
Change method for updating commands.
=> Add optional playername argument for playtime command.

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, DiscordBotPlugin/packages.config
* Fix issue #25 
* Add colour customisations
=> Fix issue #25 / Add colour customisations

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md
Add new command to show full playtime list along with 'last seen' metric.
=> Add full playtime list and last seen metric

DiscordBotPlugin/PluginMain.cs
Create a file and send it as a reply to full-playtime-list if result is >2000 characters (Discord limit)
=> Handle full list differently if reply >2000 chars

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Properties/AssemblyInfo.cs, DiscordBotPlugin/app.config, DiscordBotPlugin/packages.config
* Update for AMP 2.4
* Add command for buttonless info panel (/[botname] info nobuttons:True) #31 & #34 
* Discord.net reverted to previous version due to command builder bug
=> Buttonless Info Panel / AMP 2.4

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs
New setting for switching between http and https in manage URL (#36)
=> Add new setting for http vs https in manage URL

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs
=> Allow channel name or ID for notifications

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md
Add option to remove bot name from base command
=> Add Option to Remove Bot Name

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, DiscordBotPlugin/packages.config, README.md
Add additional optional field for info panel, can use for any additional info required (links, connection details etc)
=> Add additional field

DiscordBotPlugin/DiscordBotPlugin.csproj, DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md
Add option to send console output to a Discord channel, ref #50
=> Send Console Output to Discord Channel

DiscordBotPlugin/PluginMain.cs
Batch console output into codeblocks with a maximum of 2000 characters (Discord limit), avoid rapid firing single line outputs during high console activity.
=> Batch console output together into codeblocks

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md
Add backup button to the info panel and `take-backup` command
=> Add Backup Option

DiscordBotPlugin/PluginMain.cs
Call new method on state change and player join/leave events. Delay leave event to ensure AMP has processed the leave before updating player count.
=> Move presence update into it's own method for better response times.

DiscordBotPlugin/PluginMain.cs, DiscordBotPlugin/Settings.cs, README.md, install_script.py
* Role restriction also now takes role IDs
* Install script updated to have `--update-only` option
=> Add Role ID, update install script

DiscordBotPlugin/PluginMain.cs
Add check for player join event already processed in the last 10 seconds to avoid duplicate notifications
=> Add check for duplicate player join event

DiscordBotPlugin/Commands.cs, DiscordBotPlugin/Settings.cs
Wrap Discord chat messages for 7DTD server. Fixes #127
=> Enable sending chat from Discord for 7DTD

DiscordBotPlugin/Bot.cs
Redact password in console output. Specifically for VRising but method is now in place should other games need it.
=> Redact password in console output

DiscordBotPlugin/Bot.cs, DiscordBotPlugin/PluginMain.cs
=> Additional logging

DiscordBotPlugin/Events.cs, DiscordBotPlugin/Helpers.cs
Ignore blank player names on join/leave events, do not track leader board times #146
=> Ignore blank player names

DiscordBotPlugin/Bot.cs, DiscordBotPlugin/InfoPanel.cs
Sort online player list alphabetically
Also fix info panel response
=> Sort online player list alphabetically

DiscordBotPlugin/Events.cs, DiscordBotPlugin/Settings.cs, README.md
Add option to ignore specific text in console output
=> Add Option to Ignore Specific Text
